"""add ingest cache table

Revision ID: 884334e01440
Revises: c7f33c1fe9e7
Create Date: 2026-08-25 13:33:26.068636

"""

from collections.abc import Sequence

import sqlalchemy as sa

import kielikaveri.db.models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "884334e01440"
down_revision: str | Sequence[str] | None = "c7f33c1fe9e7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingest_cache",
        sa.Column("text_hash", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("candidates", sa.JSON(), nullable=False),
        sa.Column("created_at", kielikaveri.db.models.UTCDateTime(), nullable=False),
        sa.PrimaryKeyConstraint("text_hash"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("ingest_cache")
    # ### end Alembic commands ###
