"""srs step column, nullable stability/difficulty

Revision ID: c7f33c1fe9e7
Revises: d64d09a9e67e
Create Date: 2026-08-24 12:53:27.770583

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c7f33c1fe9e7"
down_revision: str | Sequence[str] | None = "d64d09a9e67e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("cards", sa.Column("step", sa.Integer(), nullable=True))
    op.alter_column("cards", "stability", existing_type=sa.FLOAT(), nullable=True)
    op.alter_column("cards", "difficulty", existing_type=sa.FLOAT(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("cards", "difficulty", existing_type=sa.FLOAT(), nullable=False)
    op.alter_column("cards", "stability", existing_type=sa.FLOAT(), nullable=False)
    op.drop_column("cards", "step")
    # ### end Alembic commands ###
