"""initial schema

Revision ID: d64d09a9e67e
Revises: 
Create Date: 2026-08-18 11:43:55.857930

"""
from collections.abc import Sequence

import sqlalchemy as sa

import kielikaveri.db.models
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd64d09a9e67e'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sources',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('video', 'audio', 'article', 'conversation', 'book', 'other', name='sourcetype', native_enum=False), nullable=False),
    sa.Column('ref', sa.String(), nullable=False),
    sa.Column('context_fi', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', kielikaveri.db.models.UTCDateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lemma', sa.String(), nullable=False),
    sa.Column('pos', sa.String(), nullable=True),
    sa.Column('translation_ru', sa.String(), nullable=False),
    sa.Column('example_fi', sa.String(), nullable=False),
    sa.Column('example_ru', sa.String(), nullable=False),
    sa.Column('kind', sa.Enum('word', 'pattern', name='notekind', native_enum=False), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', kielikaveri.db.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('note_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('recognition', 'production', 'inflection', 'usage', name='cardtype', native_enum=False), nullable=False),
    sa.Column('state', sa.Enum('learning', 'review', 'relearning', name='cardstate', native_enum=False), nullable=False),
    sa.Column('due', kielikaveri.db.models.UTCDateTime(), nullable=False),
    sa.Column('stability', sa.Float(), nullable=False),
    sa.Column('difficulty', sa.Float(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('card_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('reviewed_at', kielikaveri.db.models.UTCDateTime(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('cards')
    op.drop_table('notes')
    op.drop_table('users')
    op.drop_table('sources')
    # ### end Alembic commands ###
